x-common: &common
  image: mymychat:latest
  restart: unless-stopped
  volumes:
      - ./data/files:/app/files
  depends_on:
    - redis

services:
  web:
    <<: *common
    environment:
      - REDIS_URL=redis://redis:6379
    command: uvicorn asgi:application --host 0.0.0.0 --port 8000
    ports:
      - "80:8000"

  worker_llm:
    <<: *common
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python manage.py worker_llm

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
