# Generated by Django 5.2.3 on 2025-06-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20250615_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
