# Generated by Django 5.2.3 on 2025-06-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_is_shared'),
        ('userprofile', '0002_alter_systemprompt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.systemprompt'),
        ),
    ]
