# Generated by Django 5.2.3 on 2025-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
