# Generated by Django 5.2.3 on 2025-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='llm_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
