# Generated by Django 5.2.3 on 2025-06-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_prompt_llm_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
