# Generated by Django 5.2.3 on 2025-06-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemprompt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='systemprompt',
            name='name',
        ),
    ]
