name: Build and Deploy

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, us-west]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build
      run: |
        docker build -t mymychat:latest .
        docker tag mymychat:latest vital1k/mymychat:latest
        docker tag mymychat:latest vital1k/mymychat:${{ github.sha }}
        echo "Docker image built successfully!"
    
    - name: Push to Docker Hub
      run: |
        docker push vital1k/mymychat:latest
        docker push vital1k/mymychat:${{ github.sha }}
        echo "Docker images pushed to Docker Hub!"
    
    - name: Prep
      run: |
        mkdir -p /home/ubuntu/mymychat
        cp docker-compose.yml /home/ubuntu/mymychat/
    
    - name: Start
      run: |
        cd /home/ubuntu/mymychat
        docker compose up -d
        
        echo "Deployment completed successfully!"
        echo "Services status:"
        docker compose ps
