name: Build and Deploy

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: [self-hosted, us-west]
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push AMD64 image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: vital1k/mymychat:latest-amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push ARM64 image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: vital1k/mymychat:latest-arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Create and push manifest
      run: |
        docker manifest create vital1k/mymychat:latest \
          --amend vital1k/mymychat:latest-amd64 \
          --amend vital1k/mymychat:latest-arm64
        
        docker manifest create vital1k/mymychat:${{ github.sha }} \
          --amend vital1k/mymychat:latest-amd64 \
          --amend vital1k/mymychat:latest-arm64
        
        docker manifest push vital1k/mymychat:latest
        docker manifest push vital1k/mymychat:${{ github.sha }}

  deploy:
    runs-on: [self-hosted, us-west]
    needs: create-manifest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build local image for deployment
      run: |
        docker build -t mymychat:latest .
        echo "Docker image built successfully!"
    
    - name: Prep
      run: |
        mkdir -p /home/ubuntu/mymychat
        cp docker-compose.yml /home/ubuntu/mymychat/
    
    - name: Start
      run: |
        cd /home/ubuntu/mymychat
        docker compose up -d
        
        echo "Deployment completed successfully!"
        echo "Services status:"
        docker compose ps
